import Foundation
import UserNotifications
import os
import GateOpenerCore

// Compiled into BOTH the app and the widget extension (it is called from
// `OpenGateIntent`, which runs in either process). Therefore: no UIKit, no
// UIApplication. Authorization is requested ONLY from the app
// (`RootView`), never from the extension; the extension just posts.

/// Narrow seam over `UNUserNotificationCenter` so tests can fake it.
protocol NotificationCentering: Sendable {
    func authorizationStatus() async -> UNAuthorizationStatus
    func requestAuthorization(options: UNAuthorizationOptions) async throws -> Bool
    func setNotificationCategories(_ categories: Set<UNNotificationCategory>)
    func add(_ request: UNNotificationRequest) async throws
}

/// What `OpenGateIntent` (bead 6qa.4) talks to.
protocol OpenResultNotifying: Sendable {
    func registerCategories()
    func requestAuthorizationIfNeeded() async
    func postFailure(gateName: String?, message: String, pressedAt: Date) async
    func postSuccess(gateName: String?) async
    func postRetryExpired() async
}

/// Production adapter. Resolves `UNUserNotificationCenter.current()`
/// LAZILY and only when `Bundle.main.bundleIdentifier != nil` (the call
/// raises an uncatchable NSException otherwise, e.g. in a bare SwiftPM
/// process) — same rationale as `Sources/GateOpener/NotificationPresenter.swift`.
struct SystemNotificationCenter: NotificationCentering {
    private func center() -> UNUserNotificationCenter? {
        guard Bundle.main.bundleIdentifier != nil else { return nil }
        return UNUserNotificationCenter.current()
    }

    func authorizationStatus() async -> UNAuthorizationStatus {
        guard let center = center() else { return .denied }
        return await center.notificationSettings().authorizationStatus
    }

    func requestAuthorization(options: UNAuthorizationOptions) async throws -> Bool {
        guard let center = center() else { return false }
        return try await center.requestAuthorization(options: options)
    }

    func setNotificationCategories(_ categories: Set<UNNotificationCategory>) {
        center()?.setNotificationCategories(categories)
    }

    func add(_ request: UNNotificationRequest) async throws {
        guard let center = center() else { return }
        try await center.add(request)
    }
}

/// Posts the outcome of a gate open as a local notification.
///
/// - Failures are always posted when authorized; successes only when
///   `AppSettings.notifyOnOpenSuccess` is on.
/// - Every result uses ONE notification identifier, so a new result
///   REPLACES the previous one rather than stacking.
/// - Interruption level is `.active` (time-sensitive needs an entitlement
///   this app does not have — deliberately out of scope).
/// - If not authorized, `post*` are silent no-ops. Never throws.
final class OpenResultNotifier: OpenResultNotifying {
    static let failureCategoryIdentifier = "ie.boboco.GateOpener.openFailed"
    static let retryActionIdentifier = "ie.boboco.GateOpener.retryOpen"
    static let notificationIdentifier = "ie.boboco.GateOpener.openResult"
    /// userInfo key holding the press time (seconds since 1970, Double).
    static let pressedAtUserInfoKey = "pressedAt"
    /// Bundled sound file (generated by scripts/generate-failure-sound.py).
    static let failureSoundName = "gate-failed.caf"

    private static let logger = Logger(subsystem: "ie.boboco.GateOpener", category: "open-result-notifier")

    private let center: NotificationCentering
    private let settings: AppSettings

    init(settings: AppSettings, center: NotificationCentering = SystemNotificationCenter()) {
        self.settings = settings
        self.center = center
    }

    /// The failure category: ONE "Retry" action with EMPTY options (not
    /// `.foreground`, not `.authenticationRequired`) so it runs in the
    /// background without unlocking the phone.
    static func makeFailureCategory() -> UNNotificationCategory {
        let retry = UNNotificationAction(
            identifier: retryActionIdentifier,
            title: "Retry",
            options: []
        )
        return UNNotificationCategory(
            identifier: failureCategoryIdentifier,
            actions: [retry],
            intentIdentifiers: [],
            options: []
        )
    }

    func registerCategories() {
        center.setNotificationCategories([Self.makeFailureCategory()])
    }

    /// Prompts only when status is `.notDetermined`. App-only; never call
    /// from the extension.
    func requestAuthorizationIfNeeded() async {
        guard await center.authorizationStatus() == .notDetermined else { return }
        do {
            _ = try await center.requestAuthorization(options: [.alert, .sound])
        } catch {
            Self.logger.error("notification authorization request failed")
        }
    }

    func postFailure(gateName: String?, message: String, pressedAt: Date) async {
        guard await isAuthorized() else { return }
        let content = UNMutableNotificationContent()
        content.title = "Gate didn't open"
        content.body = "\(message) — tap Retry to try again"
        if let gateName { content.subtitle = gateName }
        content.categoryIdentifier = Self.failureCategoryIdentifier
        content.userInfo = [Self.pressedAtUserInfoKey: pressedAt.timeIntervalSince1970]
        content.interruptionLevel = .active
        content.sound = UNNotificationSound(named: UNNotificationSoundName(Self.failureSoundName))
        await add(content)
    }

    func postSuccess(gateName: String?) async {
        guard settings.notifyOnOpenSuccess else { return }
        guard await isAuthorized() else { return }
        let content = UNMutableNotificationContent()
        content.title = "Gate opened"
        if let gateName { content.subtitle = gateName }
        content.interruptionLevel = .active
        content.sound = .default
        await add(content)
    }

    /// Replaces the failure notification (same id) with a plain one that has
    /// NO category, hence no Retry action.
    func postRetryExpired() async {
        guard await isAuthorized() else { return }
        let content = UNMutableNotificationContent()
        content.title = "Retry expired — open GateOpener to try again"
        content.interruptionLevel = .active
        content.sound = .default
        await add(content)
    }

    private func isAuthorized() async -> Bool {
        switch await center.authorizationStatus() {
        case .authorized, .provisional, .ephemeral: return true
        default: return false
        }
    }

    private func add(_ content: UNMutableNotificationContent) async {
        let request = UNNotificationRequest(
            identifier: Self.notificationIdentifier,
            content: content,
            trigger: nil
        )
        do {
            try await center.add(request)
        } catch {
            Self.logger.error("failed to add open-result notification")
        }
    }
}
